AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  client-authentication-lbda

  Sample SAM Template for client-authentication-lbda

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  AuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authentication/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Role: arn:aws:iam::610703356069:role/LabRole # Usando a role LabRole existente
      Events:
        Authentication:
          Type: Api
          Properties:
            Path: /auth
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

Outputs:
  AuthenticationApi:
    Description: API Gateway endpoint URL for Prod stage for Authentication function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/"
  AuthenticationFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt AuthenticationFunction.Arn
  AuthenticationFunctionIamRole:
    Description: IAM Role assigned to the Lambda Function
    Value: arn:aws:iam::610703356069:role/LabRole
