name: AWS Lambda function Authentication With Sam

on:
  push:
    branches:
      - main
      - 'release/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # Empacotamento da função Lambda
      - name: Validating template using SAM
        run: sam validate

        if: startsWith(github.ref, 'refs/heads/release/') || github.ref == 'refs/heads/main'
      # Empacotamento da função Lambda
      - name: Package Lambda using SAM
        run: sam package --s3-bucket ${{ env.AWS_S3_BUCKET }} --output-template-file packaged.yaml

      # Build inside Docker containers
      - run: sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset